# 数据源配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://120.27.147.144:3306/natrp_main?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    url: jdbc:mysql://localhost:3306/natrp_main?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 941589189

 #redis 缓存数据库
#  redis:
##    host: 120.27.147.144
#    host: 127.0.0.1
#    password: 941589189
#    port: 6379
#    database: 0
#    lettuce:
#      pool:
#        # 连接池最大连接数（使用负值表示没有限制） 默认 8
#        max-active: 8
#        # 连接池最大阻塞等待时间,单位毫秒（使用负值表示没有限制） 默认 -1
#        max-wait: -1ms
#        # 连接池中的最小空闲连接
#        max-idle: 8
#        # 连接池中的最大空闲连接 默认 8
#        min-idle: 0
#      # 连接超时时间
#    timeout: 2000ms

#  ApplicationConfig/SysUserServiceImpl/SysMenuServiceImpl/SysRoleServiceImpl


